[package]
authors = ["FeÌlix Saparelli <felix@passcod.name>"]
name = "circe"
version = "0.1.0"

[dependencies]
iron = "0.5.1"
log = "0.3.8"
odbc = "0.8.1"
pretty_env_logger = "0.1.1"
serde_json = "1.0.2"

[dependencies.logger]
git = "https://github.com/iron/logger.git"
